<?php
/**
 * Minimal integration smoke test for candidate availability -> school dashboard feed.
 *
 * Usage (WP-CLI):
 *   wp eval-file wp-content/plugins/covermenowone-one/tests/availability_pipeline_integration.php
 */

if (!defined('ABSPATH')) {
    fwrite(STDERR, "This script must run inside WordPress.\n");
    exit(1);
}

$plugin = isset($GLOBALS['cmn_one_plugin']) ? $GLOBALS['cmn_one_plugin'] : null;
if (!is_object($plugin)) {
    fwrite(STDERR, "CMN plugin instance not found in \$GLOBALS['cmn_one_plugin'].\n");
    exit(1);
}

$reflector = new ReflectionClass($plugin);
$invoke = static function ($method, ...$args) use ($reflector, $plugin) {
    if (!$reflector->hasMethod($method)) {
        throw new RuntimeException("Missing method: {$method}");
    }
    $reflection_method = $reflector->getMethod($method);
    $reflection_method->setAccessible(true);
    return $reflection_method->invokeArgs($plugin, $args);
};

$created_school_id = 0;
$created_candidate_id = 0;

try {
    $created_school_id = (int) wp_insert_post([
        'post_type' => 'cmn_school',
        'post_status' => 'publish',
        'post_title' => 'CMN Availability Integration School',
    ]);
    if ($created_school_id < 1) {
        throw new RuntimeException('Unable to create school test post.');
    }
    update_post_meta($created_school_id, 'cmn_status', 'client');
    update_post_meta($created_school_id, 'cmn_location', 'London');
    delete_post_meta($created_school_id, 'cmn_postcode');

    $created_candidate_id = (int) wp_insert_post([
        'post_type' => 'cmn_candidate',
        'post_status' => 'publish',
        'post_title' => 'CMN Availability Integration Candidate',
    ]);
    if ($created_candidate_id < 1) {
        throw new RuntimeException('Unable to create candidate test post.');
    }
    update_post_meta($created_candidate_id, 'cmn_status', 'approved');
    update_post_meta($created_candidate_id, 'cmn_location', 'London');
    delete_post_meta($created_candidate_id, 'cmn_postcode');

    $timezone = wp_timezone();
    $window = $invoke('get_candidate_availability_window', new DateTime('now', $timezone));
    $target_date = isset($window['target_date']) ? (string) $window['target_date'] : '';
    if ($target_date === '' || preg_match('/^\d{4}-\d{2}-\d{2}$/', $target_date) !== 1) {
        throw new RuntimeException('Invalid target date generated by availability window helper.');
    }

    $write_result = (array) $invoke('set_candidate_morning_availability', $created_candidate_id, $target_date, true);
    if (empty($write_result['ok'])) {
        throw new RuntimeException('Failed to write candidate morning availability.');
    }

    $rows = (array) $invoke('get_school_dashboard_available_candidates', $created_school_id, 24);
    $matched = false;
    foreach ($rows as $row) {
        $post = isset($row['post']) ? $row['post'] : null;
        if ($post instanceof WP_Post && (int) $post->ID === $created_candidate_id) {
            $matched = true;
            break;
        }
    }

    if (!$matched) {
        throw new RuntimeException('Confirmed candidate not present in school availability feed.');
    }

    echo wp_json_encode([
        'ok' => true,
        'school_id' => $created_school_id,
        'candidate_id' => $created_candidate_id,
        'target_date' => $target_date,
        'confirmed_count' => (int) ($write_result['confirmed_count'] ?? 0),
        'results_count' => count($rows),
    ], JSON_PRETTY_PRINT) . PHP_EOL;
} catch (Throwable $e) {
    fwrite(STDERR, 'availability_pipeline_integration failed: ' . $e->getMessage() . PHP_EOL);
    exit(1);
} finally {
    if ($created_candidate_id > 0) {
        wp_delete_post($created_candidate_id, true);
    }
    if ($created_school_id > 0) {
        wp_delete_post($created_school_id, true);
    }
}

exit(0);
